name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - uses: FedericoCarboni/setup-ffmpeg@v3
    - name: set up ffmpeg
      with:
       # A specific version to download, may also be "release" or a specific version
       # like "6.1.0". At the moment semver specifiers (i.e. >=6.1.0) are supported
       # only on Windows, on other platforms they are allowed but version is matched
       # exactly regardless.
       ffmpeg-version: release
       # Target architecture of the ffmpeg executable to install. Defaults to the
       # system architecture. Only x64 and arm64 are supported (arm64 only on Linux).
       architecture: 'x64'
       # Linking type of the binaries. Use "shared" to download shared binaries and 
       # "static" for statically linked ones. Shared builds are currently only available
       # for windows releases. Defaults to "static"
       linking-type: static
       # As of version 3 of this action, builds are no longer downloaded from GitHub
       # except on Windows: https://github.com/GyanD/codexffmpeg/releases.
      

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download Bad Apple
      run: mkdir raw_asset && curl -L https://archive.org/download/bad-apple-resources/bad_apple%40720p60fps.ia.mp4 >> raw_asset/badapple.mp4 
    - name: Build with Gradle
      run: ./gradlew :badapple:bakeAssets && ls build
      
